apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
    namespace: argocd
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    slack-token: ENC[AES256_GCM,data:0mo6OebTHUiu4sOi1Ziobrdw3KcClq+YjB6fQkrnO+KUX9oKn42g3U85FocixnP4ND454I0pEXIZ,iv:tFklGCFsMBFZxShyg06XRD0+CW7n4y3Qje4g+dgtzmc=,tag:Y8MbNd6JEN/bSTfWAGS9gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-16T01:00:47Z"
    mac: ENC[AES256_GCM,data:9TRP0G46eD/UOggAQbG9uCzFBvliywdUzI46hU4NzGA6MDQgtj0GB/PDbj29s9Lf3sC2KtGpCdcijOWIJNywKF7uFduYNLXQm/cb0uGCAP7lYK+fD1pWed11at88J1ztEwgIsHwVHE+bGSyDt9B6yaOVWfQn9hGf3dcMYI2mjGU=,iv:4orfHhBBzQsH1DiwI6pNHGksU90nbtj0cphyh/715cU=,tag:QeIyMTma5mWKV3suvrPgAQ==,type:str]
    pgp:
        - created_at: "2022-01-16T01:00:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9aKBcudqifiARAACSVhN5cIRqsq0pa+h45VeIyn0VIQjk1Kxm6qG6sRqeYm
            Z5HHmeEad/HMho5Blm3wvvkDUmwjQB1pCA0ZrSDaam0Z9YLvD8+jctue0r8WxkvP
            ZhPN7uJoTmEf1K8ZkFrtrEcdh3yk2K9VF+1cWlzWGHDIgInQDgkHae6AzNpxuS32
            dmk1a10uRg2ctbv0iSltUwESpL0FB974eMGJBbG5+1oZ1dmj37WGfs5qcb5x4vR8
            Uvfra00Phbbzm021egfOGjfHYzNgmVgfsN8Tuo8WQwaMbBWEZuz9t3Hl2DITx6Sv
            bWndBnW6088YgvwelVtBOvIXz3QpjbaR/tb1VDL+VO6lmj4P6QkPKjtAB2EnAsVn
            vCT8H7MgZiLEEF9Hoc6TAbWw8rzinoFvrses9E6qGpXesA+yi4huqvWa0LeSohhR
            +v/xg1kXzJzg6uMg3QxsIkwwbOIjWghflebMP7JPHexP1ZVHt82m3tM5p6IgZVYn
            rl0Di5G488VmaiRc70qUvLgANXShpb7kdc5+ngHGbLlsV/7HO/4ypkkKulICj+T5
            8+m/xTFSbuG8Q6NxGI8mNMCPok8jNbUNpawnMhmlkzefBlgViNSnIM0X4QiJcMuP
            nrlEaeeZe6Z7F6bCa4Xd6JG4vY3z7ZXu/nPTubmlHVGzNjDUC/Hk2a+ZZIAvfM7S
            5gET1hBQ7hJpAS+lGdb4Cwxzrsc58kioqATe9+nwFa4ojOV5hfyKfoIyFUuX7Ves
            Zgvjezh/uwlYCWsYFqt1Aebk3o7gKcVnWlhGDUVIM9ZypOJRByfjAA==
            =EdoT
            -----END PGP MESSAGE-----
          fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(users|data|stringData)$
    version: 3.7.1
