apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-app-of-apps-osc-cl2
spec:
  destination:
    namespace: argocd
    name: moc-infra
  project: operate-first
  source:
    path: argocd/overlays/moc-infra/applications/envs/osc/osc-cl2
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
