apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/ingress-certificate
  - issuer.yaml
generators:
  - secret-generator.yaml
patchesStrategicMerge:
  - certificate.yaml
