apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: superset
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          - name: SUPERSET_IMAGE
            value: quay.io/opendatahub/superset:1.3.0
        repoRef:
          name: manifests
          path: superset
      name: superset
  repos:
    - name: manifests
      uri: https://github.com/operate-first/odh-manifests/tarball/osc-cl1-v1.1.0
  version: v1.1.0
