---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: grafana
spec:
  baseImage: quay.io/operate-first/grafana:8.4.3
  config:
    log:
      level: warn
      mode: console
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
  ingress:
    enabled: false
