---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
  - ../../../base

patchesStrategicMerge:
  - params.yaml
generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
