apiVersion: v1
kind: Secret
metadata:
    labels:
        application-crd-id: kubeflow-pipelines
    name: mlpipeline-ceph-artifact-custom
    namespace: kubeflow
stringData:
    OBJECTSTORECONFIG_HOST: ENC[AES256_GCM,data:uqZCQA15dYf8DMKFcPWgroUjdlBZy1yuNbv+SWF7VeYTloWoAvyFNyQZg8puGZ2sPY7qy/7N,iv:ZH8Ke19wm4AQlwIqvlt0fa5NJrkB+0howbFo2Fwsqpw=,tag:XlZaWglbW95juYsv3h7dFA==,type:str]
    OBJECTSTORECONFIG_PORT: ENC[AES256_GCM,data:e15K,iv:MLUp0cdSwetBap6CGzhDu2vYVAJVQXZOemk71sGjlCE=,tag:dmjs/D1NykS4IxLNspJLHg==,type:str]
    OBJECTSTORECONFIG_SECURE: ENC[AES256_GCM,data:LglyWA==,iv:IgqS70vUJviwwP8TFX93WaDmWwO4KwUbBUdsX9bu7Uc=,tag:DG8/hIG7EqKhws/+Q4dL9A==,type:str]
    OBJECTSTORECONFIG_BUCKETNAME: ENC[AES256_GCM,data:Xkqn56gHUzFBzcZDMZYZx+Tz7Vk=,iv:PZ80/5bT05sWvOpxK8lulS4NOWthOdj0y662bmwm7Xc=,tag:EYfxpe+nlnbJ2yB0d08osQ==,type:str]
    OBJECTSTORECONFIG_ACCESSKEY: ENC[AES256_GCM,data:u07lGifg+pnfBg+ZeJi19TpEpbg=,iv:HO/lsFDgkqZITBcqHUzkqxtFVbWipYvzQbG5i79P+O8=,tag:3taqQQCTwNh207gtk5FmxA==,type:str]
    OBJECTSTORECONFIG_SECRETACCESSKEY: ENC[AES256_GCM,data:+gdgjS/ZKsXkBTsxKWAztJJ9y8zvEkjvHdV3RLGTB1fxcumzqiaOPw==,iv:OmJIBNbitHuO3GCB+KwQ0sjaXIz2Xk3PNJbE6QIWXik=,tag:4fE3O94jNk6mzEGewfqhKA==,type:str]
    OBJECTSTORECONFIG_PIPELINEPATH: ENC[AES256_GCM,data:SScXobDIXqlPRg==,iv:aAjPQghYGxlufrYreoZoboCwoEIor2tt4nNa6EutAPE=,tag:EwmLw/aFfTzx94FpoLjtjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-02-28T21:09:47Z'
    mac: ENC[AES256_GCM,data:xeY4l2H2hE0uDXSd8OJcsV76Y3P+ni+PqNOEZQ3gjqYozaga7IlJBdcR8wLCwwpRDHT+AbeP3UPJ7O93KImcoFkv28vJi8c8NneOvelpe+2A2ENy+tTzBjaK7ig23CwvhiGFoiiic+L9QfSTxbot3QDFghFalBFP2IfO6/Ib1yw=,iv:VZ4NnpvMcewzPdkpZ3qb9txPqryUgttXqHEejHjH/Ys=,tag:acI4gkl1PfKvtENoA61K8g==,type:str]
    pgp:
    -   created_at: '2022-02-28T21:08:55Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9aKBcudqifiARAAAvQdwgJLEMowZMcnNaiwEZj/MWfW39UJX8U7XulNN5nt
            juHdoWznJQYuNelJ5OW9mH/oA1K9nM+dC258oWkvn7tzSG50ZBG5SclbcTa/dpVn
            kq+1N6RPuD3EW3sj9sNCr9izsU/Du52LB91Fe76w6FuEhBKDiU/B6dINlktmd3Ym
            0vvIu2UCPm4u5+94+zX+9RLANBn8DAzJAjmw8MKSrNKWbs+f96IUUiHAWYwfdZd8
            G1dqACF9CuUEiNnk5TTxXKKujeoOFB+s3HLTw1Elygt6Sk20FPsRYh2wPkKDSxi1
            h7RMLU0sgKiu0M1efCIMkjLNf2bFV6fQIOT+kaj0NSA7VAY+gk8Xjb3RwRiDesW9
            Tfic1wR7+IFuWSF6M225B3xrNXhBP9uw6S+A/Clc/uKRsDX8VRSdmT2+rzCFTjGa
            qDaMpt9M7YRizi24dsv1dRVMdydSisQw/qDkvxegZgLBppKo5IHYZ03/onxU4RRZ
            Msx0gzyQhBC50YnPVcyHlbIIcv8XjwDQfqIMwU99SYmjzgBDs3nfWWgB1ShuLgdZ
            sjVlSSr0CC41jiGUuC67fqRSsHfPhrNsrWJUrYGwdO+oBxVrzRmD+67X7waD/1cM
            WDeSKSajRcHiE8uFFVX33DUAFiEnw8VptWO9KUJu2p4GYdFzqKV6fwttx1pHjsfS
            4AHk009KBK4FIFYVyOHdSPQgReGwiuCu4F3hWhvgy+J6fBaj4K3lQ8xJGldkdnU1
            3x0aPCp+tE86gjP5whnUDF1PNP5l2XDgWuRMP9ZcAfHvKGnGIN3TUvcl4v1O6i/h
            Dc8A
            =ADGS
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(users|data|stringData)$
    version: 3.6.1
